# Higher limits for Wine/Proton (esync) and emulators - installed by setupde gaming.sh
*    soft    nofile     524288
*    hard    nofile     1048576
*    soft    memlock    unlimited
*    hard    memlock    unlimited
